redash:
  build: .
  ports:
    - "5000:5000"
    - "9001:9001"
  links:
    - redis
    - postgres
  stdin_open: true
redis:
  image: redis:3.0
  ports:
    - "6379:6379"
postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"
